---
#########################
#########################
## Deploy Docker Image ##
#########################
#########################

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#######################################
# Start the job on all push to main #
#######################################
name: "Build & Deploy - RELEASE"
on:
  release:
    # Want to run the automation when a release is created
    types: ["created"]
    paths:
      - "Dockerfile"
      - "megalinter/**"
      - "mega-linter-runner/**"
      - "flavors/**"
      - "**/linter-versions.json"
      - "**/.sh"

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Deploy Docker Image - RELEASE
    # Set the agent to run on
    runs-on: ubuntu-latest
    # Only run on main repo
    if: github.repository == 'oxsecurity/megalinter' && !contains(github.event.head_commit.message, 'skip deploy')
    environment:
      name: latest
    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3

      ########################################################
      # Publish updated version of mega-linter-runner on NPM #
      ########################################################
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
      - run: cd mega-linter-runner && npm install
      - run: cd mega-linter-runner && npm publish || echo "mega-linter-runner not published"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      ###################################
      # Run Deploy script for Dockerhub #
      ###################################
      - name: Deploy Release image to Dockerhub
        env:
          # Set the Env Vars
          GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_REPO: oxsecurity/megalinter
          IMAGE_VERSION: ${{ github.event.release.tag_name }}
          DOCKERFILE_PATH: Dockerfile
          DOCKER_BUILD_PLATFORMS: linux/amd64
          REGISTRY: Docker
        shell: bash
        run: .automation/upload-docker.sh

      ###################################################
      # Run Deploy script for GitHub Container Registry #
      ###################################################
      - name: Deploy Release image to GitHub Container Registry
        env:
          # Set the Env Vars
          GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GCR_USERNAME: ${{ secrets.GCR_USERNAME }}
          GCR_TOKEN: ${{ secrets.GCR_PASSWORD }}
          IMAGE_REPO: oxsecurity/megalinter
          IMAGE_VERSION: ${{ github.event.release.tag_name }}
          DOCKERFILE_PATH: Dockerfile
          DOCKER_BUILD_PLATFORMS: linux/amd64
          REGISTRY: GCR
        shell: bash
        run: .automation/upload-docker.sh

      # Free disk space
      - name: Free Disk space
        shell: bash
        run: |
          sudo rm -rf /usr/local/lib/android  # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET

  deploy_doc:
    runs-on: ubuntu-latest
    needs: build
    if: github.repository == 'oxsecurity/megalinter'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get release version
        id: version
        run: |
          {
            echo "cversion=$(git describe --tags --match='v*' --abbrev=0 | cut -c2-)"
            echo "ctag=$(git describe --tags --match='v*' --abbrev=0)"
            echo "pversion=$(git describe --abbrev=0 --match='v*' --tags "$(git rev-list --tags --skip=1 --max-count=1)" | cut -c2-)"
            echo "ptag=$(git describe --abbrev=0 --match='v*' --tags "$(git rev-list --tags --skip=1 --max-count=1)")"
          } >>"$GITHUB_OUTPUT"
      - name: Print tags
        run: |
          echo "prev tag ${{ steps.version.outputs.ptag }}"
          echo "curr tag ${{ steps.version.outputs.ctag }}"
          echo "prev ver ${{ steps.version.outputs.pversion }}"
          echo "curr ver ${{ steps.version.outputs.cversion }}"
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.x
      - run: pip install --upgrade markdown==3.3.7 mike mkdocs-material mdx_truly_sane_lists json-schema-for-humans giturlparse webpreview
      - run: cd .automation && bash build_schemas_doc.sh && cd ..
      # - run: mkdocs gh-deploy --force
      - run: |
          git config --global user.name megalinter-bot
          git config --global user.email megalinter@megalinter.com
          git stash
      - name: Checkout previous tag
        run: |
          git checkout ${{ steps.version.outputs.ptag }}
      - name: Mike deploy previous version
        run: |
          mike delete ${{ steps.version.outputs.pversion }} || echo 'version does not exists yet'
          mike deploy ${{ steps.version.outputs.pversion }}
      - name: Checkout current tag
        run: |
          git checkout ${{ steps.version.outputs.ctag }}
      - name: Mike deploy current version
        run: |
          mike delete latest
          mike delete v6 || true
          mike deploy v6 || true
          mike deploy --push latest ${{ steps.version.outputs.cversion }}
