---
#########################
#########################
## Deploy Docker Image Flavors ##
#########################
#########################
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#######################################
# Start the job on all push to main #
#######################################
name: "Build & Deploy - Release linters"
on:
  release:
    # Want to run the automation when a release is created
    types: ["created"]
    paths:
      - "Dockerfile"
      - "megalinter/**"
      - "flavors/**"
      - "**/linter-versions.json"
      - "**/.sh"

###############
# Set the Job #
###############
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  build:
    # Name the Job
    name: Deploy Docker Image - Release - Linters
    # Set the agent to run on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # linters-start
        linter:
          [
            "ansible_ansible_lint",
            "bash_shellcheck",
            "cloudformation_cfn_lint",
            "dockerfile_hadolint",
            "go_revive",
            "groovy_npm_groovy_lint",
            "java_checkstyle",
            "java_pmd",
            "javascript_es",
            "json_eslint_plugin_jsonc",
            "jsx_eslint",
            "kotlin_ktlint",
            "php_psalm",
            "python_bandit",
            "repository_checkov",
            "repository_devskim",
            "repository_dustilock",
            "repository_gitleaks",
            "repository_secretlint",
            "repository_semgrep",
            "repository_syft",
            "repository_trivy",
            "terraform_tflint",
            "terraform_terrascan",
            "terraform_checkov",
            "tsx_eslint",
            "typescript_es",
          ]
# linters-end
    # Only run this on the main repo
    if: github.repository == 'oxsecurity/megalinter' && !contains(github.event.head_commit.message, 'skip deploy')
    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3

      ###################################
      # Run Deploy script for Dockerhub #
      ###################################
      - name: Deploy ${{ github.event.release.tag_name }} image to DockerHub
        env:
          # Set the Env Vars
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_REPO: oxsecurity/megalinter-only-${{ matrix.linter }}
          IMAGE_VERSION: "${{ github.event.release.tag_name }}"
          DOCKERFILE_PATH: linters/${{ matrix.linter }}/Dockerfile
          DOCKER_BUILD_PLATFORMS: linux/amd64
          REGISTRY: Docker
          ALWAYS_BUILD: force
        shell: bash
        run: .automation/upload-docker.sh

      ###################################################
      # Run Deploy script for GitHub Container Registry #
      ###################################################
      - name: Deploy ${{ github.event.release.tag_name }} image to GitHub Container Registry
        env:
          # Set the Env Vars
          GCR_USERNAME: ${{ secrets.GCR_USERNAME }}
          GCR_TOKEN: ${{ secrets.GCR_PASSWORD }}
          IMAGE_REPO: oxsecurity/megalinter-only-${{ matrix.linter }}
          IMAGE_VERSION: "${{ github.event.release.tag_name }}"
          DOCKERFILE_PATH: linters/${{ matrix.linter }}/Dockerfile
          DOCKER_BUILD_PLATFORMS: linux/amd64
          REGISTRY: GCR
          ALWAYS_BUILD: force
        shell: bash
        run: .automation/upload-docker.sh

      #####################################
      # Run Linter test cases #
      #####################################
      - name: Run Test Cases
        shell: bash
        run: |
          TEST_KEYWORDS_TO_USE_UPPER="${{ matrix.linter }}"
          TEST_KEYWORDS_TO_USE="${TEST_KEYWORDS_TO_USE_UPPER,,}"
          docker run -e TEST_CASE_RUN=true -e OUTPUT_FORMAT=text -e OUTPUT_FOLDER=${GITHUB_SHA} -e OUTPUT_DETAIL=detailed -e GITHUB_SHA=${GITHUB_SHA} -e PAT="${{secrets.PAT}}" -e TEST_KEYWORDS="${TEST_KEYWORDS_TO_USE}" -e MEGALINTER_VOLUME_ROOT="${GITHUB_WORKSPACE}" -v "/var/run/docker.sock:/var/run/docker.sock:rw" -v ${GITHUB_WORKSPACE}:/tmp/lint oxsecurity/megalinter-only-${{ matrix.linter }}:${{ github.event.release.tag_name }}
        timeout-minutes: 30

      ##############################################
      # Check Docker image security with Trivy #
      ##############################################
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/oxsecurity/megalinter-only-${{ matrix.linter }}:${{ github.event.release.tag_name }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          security-checks: vuln
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          timeout: 10m0s
