---
#########################
#########################
## Deploy Docker Image Flavors ##
#########################
#########################

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#######################################
# Start the job on all push to main #
#######################################
name: "Build & Deploy - BETA Flavors"
on:
  push:
    branches:
      - "main"
      - "FlavoredMegaLinters"
    paths:
      - ".github/workflows/**"
      - "Dockerfile"
      - "flavors/**"
      - "megalinter/**"
      - "mega-linter-runner/**"
      - "**/linter-versions.json"
      - "TEMPLATES/**"
      - ".trivyignore"
      - "**/.sh"

###############
# Set the Job #
###############
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  build:
    # Name the Job
    name: Deploy Docker Image - BETA - Flavors
    # Set the agent to run on
    runs-on: ${{ matrix.os }}
    environment: 
      name: beta-flavors
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # flavors-start
        flavor:
          [
            "ci_light",
            "cupcake",
            "documentation",
            "dotnet",
            "go",
            "java",
            "javascript",
            "php",
            "python",
            "ruby",
            "rust",
            "salesforce",
            "security",
            "swift",
            "terraform",
          ]
# flavors-end
    # Only run this on the main repo
    if: github.repository == 'oxsecurity/megalinter' && !contains(github.event.head_commit.message, 'skip deploy')
    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3

      ###################################
      # Run Deploy script for Dockerhub #
      ###################################
      - name: Deploy beta image to DockerHub
        env:
          # Set the Env Vars
          GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_REPO: oxsecurity/megalinter-${{ matrix.flavor }}
          IMAGE_VERSION: beta
          DOCKERFILE_PATH: flavors/${{ matrix.flavor }}/Dockerfile
          DOCKER_BUILD_PLATFORMS: linux/amd64
          REGISTRY: Docker
        shell: bash
        run: .automation/upload-docker.sh

      ###################################################
      # Run Deploy script for GitHub Container Registry #
      ###################################################
      - name: Deploy beta image to GitHub Container Registry
        env:
          # Set the Env Vars
          GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GCR_USERNAME: ${{ secrets.GCR_USERNAME }}
          GCR_TOKEN: ${{ secrets.GCR_PASSWORD }}
          IMAGE_REPO: oxsecurity/megalinter-${{ matrix.flavor }}
          IMAGE_VERSION: beta
          DOCKERFILE_PATH: flavors/${{ matrix.flavor }}/Dockerfile
          DOCKER_BUILD_PLATFORMS: linux/amd64
          REGISTRY: GCR
        shell: bash
        run: .automation/upload-docker.sh

      # Free disk space
      - name: Free Disk space
        shell: bash
        run: |
          sudo rm -rf /usr/local/lib/android  # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET

      ##############################################
      # Check Docker image security with Trivy #
      ##############################################
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/oxsecurity/megalinter-${{ matrix.flavor }}:beta'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          security-checks: vuln
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          timeout: 10m0s
