---
name: "Test mega-linter-runner"
on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Test MegaLinter runner
    # Set the agent to run on
    runs-on: ubuntu-latest
    # Prevent duplicate run from happening when a forked push is committed
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    timeout-minutes: 60
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: "12"
      - name: Use Docker in rootless mode.
        uses: ScribeMD/rootless-docker@0.2.2
      - name: Install dependencies
        run: cd mega-linter-runner && yarn install --frozen-lockfile && npm link
      - name: Run CLI tests
        run: cd mega-linter-runner && mocha test/megalinter-cli.test.js
      - name: Run module tests
        run: cd mega-linter-runner && mocha test/megalinter-module.test.js
      - name: Run upgrade tests
        run: cd mega-linter-runner && mocha test/megalinter-upgrade.test.js
